# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##
wordpress:
  ## @param wordpressUsername WordPress username
  ##
  wordpressUsername: admin
  wordpressPassword: "wordpress"
  wordpressBlogName: UCP User's Blog!

  replicaCount: 1

  ## @section Persistence Parameters
  ##

  ## Persistence Parameters
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    storageClass: "vsp-186-sc"
    size: 2Gi

  ## MariaDB chart configuration
  ## ref: https://github.com/bitnami/charts/blob/main/bitnami/mariadb/values.yaml
  ##
  mariadb:
    ## @param mariadb.architecture MariaDB architecture. Allowed values: `standalone` or `replication`
    ##
    architecture: replication
    ## MariaDB Primary configuration
    ##
    primary:
      ## MariaDB Primary Persistence parameters
      persistence:
        storageClass: "vsp-e1090-nvme-sc"
        size: 4Gi
    secondary:
      persistence:
        storageClass: "vsp-e1090-nvme-sc"
        size: 4Gi
