apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization

  resources:
    - yaml/hspc-operator-namespace.yaml
    - yaml/regcred-redhat-com.yaml
    - yaml/regcred-redhat-io.yaml
    - yaml/hspc-operator.yaml
    - yaml/hspc_v1_hspc.yaml